all:
	make -C Useful
	make -C Game_Treatment
	make -C AI_Data
	make -C AI_Functions
	make -C Main

realclean:
	make -C Useful realclean
	make -C Game_Treatment realclean
	make -C AI_Data realclean
	make -C AI_Functions realclean
	make -C Main realclean